sudo: required
language: python
python:
 - '3.6'
install:
 - pip install -r requirements.txt
 - python setup.py install
 - pip install coveralls
before_script:
 - sleep 3
script:
 - coverage run --source=xrayMP ./checks.py
after_success: coveralls